# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'f5sell' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for f5sell

  target 'f5sell-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'f5sellTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'f5sell-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for f5sell-tvOS

  target 'f5sell-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
